version: '3.8'

services:
  app:
    container_name: play_ke_gateway
    image: osiru/play-ke-content:${BACKEND_TAG}
    working_dir: /usr/src/app
    ports:
      - "8021:8021"
    depends_on:
      - postgres
    environment:
      - ENV=production
      - DEBUG=0
      - DJANGO_SECRET_KEY=django-insecure-fmq&5@^#yv*$lmqc8o+q(_#v)_9n#&u*_=lwz+=ty^@)6b@v=m
      - USE_S3=0
      - ALLOWED_HOST=*
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DB_IGNORE_SSL=true
    volumes:
      - .:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - play_ke_gateway_logs:/var/log/play-ke-content
    networks:
      - play_ke_gateway_app_net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.5"

  postgres:
    image: postgres:16
    ports:
      - "5445:5432"
    volumes:
      - play_ke_gateway_app_pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - play_ke_gateway_app_net
    deploy:
      resources:
        limits:
          memory: 1G


volumes:
  portainer_data:
  play_ke_gateway_app_pg:
  play_ke_gateway_logs:
    driver: local

networks:
  play_ke_gateway_app_net:
    driver: bridge
