# Generated by Django 5.1.4 on 2025-04-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthclient',
            name='client_id',
            field=models.CharField(default='ssp48ozUD8VFx3PwZW7jI2nE9gCzSgUQUqXz19UIDKGQMsJfi1Ka28BxB-g1Y-8d11E', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='oauthclient',
            name='client_secret',
            field=models.CharField(default='fkw5i5_-1O6vBfYkQs7WF8oi_HO7dy8TkLzXX-hIpf_B2TFltQfT4nKu2YUZRyIkogtUI9Qd12Zc1gJVYIWg3Yd03-NZeAMETkx4Q8ZBoJMtNP52py-76QM3rA5WYvaIqqneKw', max_length=500, unique=True),
        ),
    ]
