# Generated by Django 5.1.4 on 2025-04-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_accesstoken_state_alter_oauthclient_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthclient',
            name='client_id',
            field=models.CharField(default='zm7D2AGl1sAwX-5xKDrr9Kyn_423MnutFlYI5FVpWcfJppZYt2OSDbIboYsduq7Y3vSSJHfywaPZOom-7c7_6w', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='oauthclient',
            name='client_secret',
            field=models.CharField(default='qBUScvhImvHiYWI_rk-kqJZmmdnRYsyHaRDxRrd2xC8TFS1dnEsCPw4lGmSpU6IjsDKRy_39IJGCa_UEXdW6UchttdlGJgA7KoFiO45GifGiAjZBPw-4_WzCWNLCDR8kd0YtfCW3lsji82vpeENf7XgUWQWgvBP1eDKByVgv3gI', max_length=128, unique=True),
        ),
    ]
