# Generated by Django 5.1.4 on 2025-04-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_oauthclient_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthclient',
            name='client_id',
            field=models.CharField(default='dczeJUUUVobF2S8IgllBAZCSKPWaEVRlc0fCp5n4wuPbm03AXfjgLF0xCl95OpT_9EQj-XykE8Hu2UCNKKs0sw', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='oauthclient',
            name='client_secret',
            field=models.CharField(default='teV-4Ad9Hk1cVsOYwQvHtBTkpG_xgr5hAHrK0kS3p3ndM4Eb-Qni_9CFoAP_8eUSdJ7nGTaH_d3Fqzh_hktQGp0ENiCm5s0q7XlwdRkk_UgQyaQLMYX1NCnt8-8F0bxO4caJUnPC9lBX3LgVGPvaNHvfZYO-RlxOFA2SDHL3DBI', max_length=256, unique=True),
        ),
    ]
